[package]
name = "spider-bot"
version = "0.1.0"
authors = ["Stefan Breetveld <spiderbiggen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread"] }