[package]
name = "spider-bot"
version = "0.1.0"
authors = ["Stefan Breetveld <spiderbiggen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kitsu = { path = "kitsu" }
nyaa = { path = "nyaa" }
giphy = { path = "giphy" }
chrono = "^0.4"
diesel = { version = "^1.4.6", features = ["chrono", "postgres"] }
dotenv = "^0.15.0"
lazy_static = "^1.4.0"
rand = "^0.8.3"
reqwest = { version = "^0.11", features = ["json"] }
serenity = "^0.10"
tokio = { version = "^1.4.0", features = ["macros", "rt-multi-thread"] }

[workspace]
members = [
    "giphy",
    "kitsu",
    "nyaa",
]
