[package]
name = "spider-bot"
version = "0.1.6"
authors = ["Stefan Breetveld <spiderbiggen@gmail.com>"]
edition = "2021"
description = "Discord bot for the 'Turtle Force' discord"

[workspace]
members = [
    "tenor",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tenor = { path = "tenor" }

async-trait = "0.1.74"
anyhow = "1.0.75"
chrono = "0.4.19"
dotenv = "0.15.0"
futures = "0.3.21"
rand = "0.8.5"
thiserror = "1.0.30"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
native-tls = { version = "0.2.1", features = ["vendored"]}
itertools = "0.11.0"

[dependencies.serenity]
version = "0.11.6"
default-features = false
features = [
    "client",
    "gateway",
    "native_tls_backend",
    "model",
    "cache",
    "temp_cache"
]

[dependencies.tokio]
version = "1.33.0"
features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "time"
]
