[package]
name = "spider-bot"
version = "0.1.0"
authors = ["Stefan Breetveld <spiderbiggen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kitsu = { path = "kitsu", optional = true }
nyaa = { path = "nyaa", optional = true }
giphy = { path = "giphy", optional = true }
tenor = { path = "tenor", optional = true }
chrono = "^0.4"
dotenv = "^0.15"
futures = "^0.3"
rand = "^0.8.4"
reqwest = { version = "^0.11", features = ["json"] }
serenity = { version = "^0.10", features = ["unstable_discord_api"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
unicode-segmentation = "1"

[workspace]
members = [
    "giphy",
    "kitsu",
    "nyaa",
    "tenor",
]

[features]
default = ["tenor", "anime-fetch"]
anime = ["kitsu", "anime-fetch"]
anime-fetch = ["nyaa"]
