[package]
name = "spider-bot"
version = "0.1.0"
authors = ["Stefan Breetveld <spiderbiggen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
diesel = { version = "1.4.6", features = ["postgres"] }
dotenv = "0.15.0"
futures = { version = "0.3.*" }
lazy_static = "1.4.0"
magnet-url = "1.2.1"
rand = "0.8.3"
regex = "1.4.3"
reqwest = { version = "0.11", features = ["json"] }
rss = "1.0"
serde = { version = "1.0.123", features = ["derive"] }
serenity = "0.10"
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread"] }
url = "2.2.0"
