[package]
name = "spider-bot"
version = "0.1.0"
authors = ["Stefan Breetveld <spiderbiggen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kitsu = { path = "kitsu" }
nyaa = { path = "nyaa" }
giphy = { path = "giphy", optional = true }
tenor = { path = "tenor", optional = true }
anyhow = "1.0.41"
chrono = "^0.4"
diesel = { version = "^1.4.6", features = ["chrono", "postgres"] }
dotenv = "^0.15.0"
futures = "^0.3.*"
rand = "^0.8.3"
reqwest = { version = "^0.11", features = ["json"] }
serenity = { version = "^0.10.8", features = ["unstable_discord_api"] }
tokio = { version = "^1.4.0", features = ["macros", "rt-multi-thread"] }
unicode-segmentation = "^1.7.1"

[workspace]
members = [
    "giphy",
    "kitsu",
    "nyaa",
    "tenor",
]

[features]
default = ["giphy", "tenor"]
anime = []
anime_storage = ["anime"]
