[package]
name = "otaku"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
proto = { path = "../proto" }

chrono = "0.4.38"
futures-util = "0.3.28"
prost-types = "0.12.4"
thiserror = "1.0.61"
tokio = "1"
tonic = { version = "0.11.0", features = ["gzip"] }
tracing = "0.1.40"

[dependencies.sqlx]
version = "0.7.4"
features = ["postgres", "runtime-tokio-rustls", "chrono", "uuid"]
