[package]
name = "db"
version = "0.1.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
domain = { path = "../domain" }

futures-util = "0.3.28"
thiserror = { workspace = true }
tracing = { workspace = true }

[dependencies.sqlx]
version = "0.9.0"
features = ["postgres", "runtime-tokio", "tls-rustls-aws-lc-rs", "chrono", "uuid"]
